docs/DeveloperGuide.md
docs/UserGuide.md
docs/team/tiongjjyi.md

Add tiongjjyi.md

---

src/main/java/seedu/address/model/info/course/Course.java
src/main/java/seedu/address/model/info/course/CourseList.java

Add JavaDoc to fix GitHub Actions.

Add JavaDoc for course package

---

README.md
docs/DeveloperGuide.md

Update README.md to match project

---

docs/UserGuide.md

Reverts AY2324S1-CS2103T-W15-4/tp#55

Revert "Update UG v2.0"

---

src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
src/test/java/seedu/address/testutil/StudentBuilder.java
src/test/java/seedu/address/testutil/TestUtil.java
src/test/java/seedu/address/testutil/TypicalCourses.java
src/test/java/seedu/address/testutil/TypicalStudents.java

The testcases in RemarkCommandTest are modified according to the new structure of our project.

Modify and add testcase for RemarkCommand

---

src/main/java/seedu/address/ui/CombinedPanel.java
src/main/java/seedu/address/ui/CourseListPanel.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/CombinedPanel.fxml
src/main/resources/view/MainWindow.fxml

Fixes #95 
checkstyleMain ran and passed.

Change UI for Student stage

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/model/person/AllPendingQuestionPredicate.java

Find command:
1. `find John` to find student with name **John**.
2. `find pq` to find **all** existing question.

Enable finding all existing questions

---

docs/DeveloperGuide.md

Update Add a Pending Question to a Student under Implementation in DeveloperGuide.md

Update Adding PQ implementation in DG

---

src/main/java/seedu/address/logic/parser/StageManager.java
src/main/java/seedu/address/ui/CourseCard.java
src/main/java/seedu/address/ui/CourseListPanel.java
src/main/java/seedu/address/ui/StudentCard.java
src/main/resources/view/CourseListCard.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/StudentListPanel.fxml

UI changes made for Tags in both Course and Student Cards to be displayed in respective colours. 
In the combined panel screen's course list sidebar (after selecting a course), the courses not selected will be faded to emphasise the current selected course
Fixes #121

Make UI changes

---

src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/ClearCourseCommand.java
src/main/java/seedu/address/logic/parser/CodeSphereParser.java
src/main/java/seedu/address/model/course/Course.java
src/main/java/seedu/address/model/person/UniqueStudentList.java

Current ClearCommand incorrectly cleared the course list. Added a ClearCourseCommand and changed ClearCommand to clear the student list.

Add ClearCourseCommand and edit ClearCommand

---

docs/UserGuide.md
src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/HelpWindow.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/UiManager.java

Command History can now be viewed using the up and down arrow keys.
Fixes #157

Add Command History

---

src/main/java/seedu/address/ui/CommandBox.java

Double variables declared, rendering program temporarily unusable

Fix UI double variable bug

---

docs/UserGuide.md

Remove `find pq` feature in UG and minor edits.

Minor UG edits

---

src/main/java/seedu/address/ui/DisplayPanel.java
src/main/java/seedu/address/ui/MainWindow.java

Fix splash screen bug

---

docs/UserGuide.md
src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/storage/InputHistory.java
src/main/java/seedu/address/storage/InputStorage.java
src/main/java/seedu/address/ui/CommandBox.java

Change the colour of the previously view input history, and add documentation

Make UI changes for input history

---

src/main/resources/view/CourseListCard.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/StudentListCard.fxml

Make app UI changes

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/commands/HomeCommand.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/predicates/PqContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/predicates/RemarkContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/predicates/TagFilterPredicate.java

Fix find bug for unordered words.
If user types in find n/Doe John, the UI should display John Doe.
Let's fix this by editing the logic of the StringUtil containsIgnoreCase
command.
This will let users to find words better and improve UX.

Fix Find Bug

---

src/test/java/seedu/address/logic/commands/FindCourseCommandTest.java
src/test/java/seedu/address/logic/commands/HelpCommandTest.java
src/test/java/seedu/address/logic/parser/FindCourseCommandParserTest.java
src/test/java/seedu/address/testutil/TypicalCourses.java

Also do a fix for HelpCommandTest.

Add FindCourseCommandTest and FindCourseCommandParserTest

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteCourseCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/course/Course.java
src/main/java/seedu/address/model/person/Email.java
src/test/java/seedu/address/logic/MessagesTest.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/AddCourseCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteCourseCommandTest.java
src/test/java/seedu/address/logic/commands/SelectCommandTest.java
src/test/java/seedu/address/model/person/EmailTest.java
src/test/java/seedu/address/testutil/CourseBuilder.java

Add SelectCommandTest.java
Updated other test files

Updated files for testing

---

src/main/java/seedu/address/model/course/Course.java
src/test/java/seedu/address/model/course/CourseTest.java

Fix CourseTest.java

---

src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/model/course/CourseNameTest.java

CourseNameTest.java now passes all tests

Fix CourseNameTest.java

---

src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/model/person/NameTest.java

Fixed name regex as well as related NameTest.java
Fixes #207

Fix name tests and name regex

---

docs/UserGuide.md

Addressed issues/documentation bugs #215, #216, #226, and #233.

Fix UserGuide.md

---

src/main/resources/view/CourseListCard.fxml
src/main/resources/view/MainWindow.fxml

FXML files updated to fit with java code changes

Fix .fxml files

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/MainWindow.fxml

Fix checkstyle errors for app

---

src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteCourseCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/EditCourseCommandTest.java
src/test/java/seedu/address/logic/commands/HomeCommandTest.java
src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
src/test/java/seedu/address/logic/commands/ResetCommandTest.java
src/test/java/seedu/address/logic/commands/SelectCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
src/test/java/seedu/address/logic/parser/ClearCourseCommandParserTest.java
src/test/java/seedu/address/logic/parser/CodeSphereParserTest.java
src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
src/test/java/seedu/address/testutil/CourseBuilder.java
src/test/java/seedu/address/testutil/StudentUtil.java

Fix code regarding checkstyle for tests

Fix checkstyle for tests

---

src/main/java/seedu/address/ui/StudentCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/StudentListCard.fxml

Text now wraps according to application window size
Fixes #230, #225, #221

Implement text wrap for student card
